/run/verbose 1
/run/initialize
/gun/sourceGen false
/gps/particle e-
/gps/pos/type   Plane
/gps/pos/shape  Circle
/gps/pos/radius 10 cm
/gps/pos/rot1 1 0 -0
/gps/pos/rot2 0 1 0
/gps/pos/centre 0 0 30
/gps/direction -0 -0 -1

/gps/hist/type biasy 
/gps/hist/point 0. 0. 
/gps/hist/point 0.5 0. 
/gps/hist/point 1.0 1.

/gps/ene/type Pow
/gps/ene/alpha -1
/gps/ene/min 10 keV
/gps/ene/max 100 GeV
/run/beamOn 1000000