/run/verbose 1
/run/initialize
/gun/sourceGen false
/gps/particle  geantino
/gps/pos/type  Surface 
/gps/pos/shape Sphere
/gps/pos/centre 0. 0. 0. cm
/gps/pos/radius 16. cm
/gps/pos/rot1 0 0 1
/gps/pos/rot2 1 0 0
#/gps/direction 0 0 1
/gps/ang/type cos
/gps/ang/rot1 0 0 1
/gps/ang/rot1 1 0 0
#/gps/ang/mintheta 90
/gps/ang/maxtheta 180

/gps/hist/type biaspt 
#/gps/hist/point 0. 0. 
#/gps/hist/point 0.5 1. 
#/gps/hist/point 1.0 0.
/gps/hist/point 0. 0. 
/gps/hist/point 0.333 0. 
/gps/hist/point 0.5 1. 
/gps/hist/point 1.0 0.

/gps/hist/type biaspp 
/gps/hist/point 0. 0. 
/gps/hist/point 0.0416 1.
/gps/hist/point 0.9584 0. 
/gps/hist/point 1.0 1.

#/gps/hist/point 0. 0. 
#/gps/hist/point 0.0416 1.
#/gps/hist/point 0.99584 0. 
#/gps/hist/point 1.0 1.

/gps/ene/type Pow
/gps/ene/alpha -1
/gps/ene/min 10  keV
/gps/ene/max 100 GeV
/run/beamOn 10000
